#!/bin/bash
  
#put result of the command date+%d-%m-%y in a variable

DATE=$(date +%d-%m-%y)
echo $DATE

echo the day is ${DATE%%-*}
MONTH=${DATE%-*}
echo the month is ${MONTH#*-}
echo the year is ${YEAR##*-}


